export const data = [
	{
		id: 1,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: 120,
	},
	{
		id: 2,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Draft',
		stats: 0,
	},
	{
		id: 3,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Schedule',
		stats: 120,
	},
	{
		id: 4,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: -2,
	},
	{
		id: 5,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: 120,
	},
	{
		id: 6,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: 120,
	},
	{
		id: 7,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Draft',
		stats: 0,
	},
	{
		id: 8,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Schedule',
		stats: 120,
	},
	{
		id: 9,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: 1,
	},
	{
		id: 10,
		title: 'Design: A Survival Guide for Beginners',
		date: '3 Days Ago',
		status: 'Published',
		stats: 120,
	},
]
